include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # - public_member_api_docs
    - camel_case_types
    - prefer_collection_literals
    - avoid_shadowing_type_parameters
    - do_not_use_environment
    - no_runtimeType_toString
    - unawaited_futures
    - avoid_type_to_string
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_private_typedef_functions
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - deprecated_consistency
    - directives_ordering
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - noop_primitive_operations
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    # - prefer_final_parameters
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - sort_pub_dependencies

analyzer:
  language:
    strict-raw-types: true

  # strong-mode:
  #   implicit-casts: false

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
