FROM ubuntu:22.10

RUN apt update

# General
RUN apt install git -y

# FFMPEG
RUN apt install ffmpeg -y

# Flutter
RUN apt install zip xz-utils curl libglu1-mesa -y
RUN cd / && git clone -b master https://github.com/flutter/flutter.git
RUN export PATH="$PATH:/flutter/bin"
RUN flutter precache & flutter doctor

# Flutter Linux Toolchain
RUN apt install clang cmake ninja-build pkg-config libgtk-3-dev -y
RUN apt install upx -y
