name: osumffmpeg
description: Power of FFMPEG for normal users.
publish_to: 'none'
homepage: https://aswinmurali-io.github.io/osumffmpeg/
repository: https://github.com/aswinmurali-io/osumffmpeg

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animate_do: ^3.3.4
  archive: ^3.3.0
  async: ^2.9.0
  ffmpeg_kit_flutter_full: ^6.0.3
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_typeahead: ^4.0.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1 #
  osumlog: ^0.1.0
  path: ^1.8.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  web_smooth_scroll: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
