name: osumffmpeg
description: Power of FFMPEG for normal users.
publish_to: 'none'
homepage: https://aswinmurali-io.github.io/osumffmpeg/
repository: https://github.com/aswinmurali-io/osumffmpeg

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animate_do: ^2.1.0
  async: ^2.9.0
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_hooks: ^0.18.4
  flutter_riverpod: ^1.0.4 #
  flutter_typeahead: ^4.0.0
  osumlog: ^0.1.0
  path: ^1.8.0
  shared_preferences: ^2.0.15
  web_smooth_scroll: ^1.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
