name: osumffmpeg
description: Power of FFMPEG for normal users.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-168.0.dev <3.0.0'

dependencies:
  animate_do: ^2.1.0
  async: ^2.9.0
  dropdown_search: ^5.0.2
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_hooks: ^0.18.4
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4
  osumlog: ^0.1.0
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
