name: osumffmpeg
description: Provide the power of `ffmpeg` to normal users.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-168.0.dev <3.0.0'

dependencies:
  animate_do: ^2.1.0
  dropdown_search: ^5.0.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_riverpod: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
