name: osumffmpeg
version: git
summary: Power of FFMPEG for normal users.
description: 𝗢𝘀𝘂𝗺 𝗙𝗙𝗠𝗣𝗘𝗚 is a 📹 media utility tool 🛠️ that gives the normal users the power of FFMPEG 💪 to convert formats ⚙️ • loop video 🔁 • mute audio 🔇 and much more in a beautiful UI.

confinement: strict
base: core18
grade: devel
compression: xz

parts:
  osumffmpeg:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart

apps:
  osumffmpeg:
    command: osumffmpeg
    extensions:
      - flutter-beta
    plugs:
      - network
      - desktop
