name: Code Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Create platform
        run: flutter create .

      # - name: Run tests
      #   run: flutter test

      - name: Upload source code
        uses: actions/upload-artifact@v3
        with:
          name: osumffmpeg-source
          path: .
