name: flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: 3.1.0

      # source: https://github.com/flutter/flutter/issues/59750
      - name: Patch for linux build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
      
      - name: Create platform
        run: flutter create .

      - name: Test Build
        run: flutter build linux

#       - name: Run tests
#         run: flutter test
