name: Inno Setup

on:
  workflow_run:
    workflows: ["Windows Build"]
    types:
      - completed

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Get app
        uses: actions/download-artifact@v3
        with:
          name: osumffmpeg-windows-x64-noffmpeg

      - name: Get innosetup
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install innosetup -y

      - name: Build installer
        run: iscc innosetup.iss

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: osumffmpeg-windows-x64-noffmpeg-installer.exe
          path: build/windows/installer/Osumffmpeg Installer.exe
