name: Linux Build

on:
  workflow_run:
    workflows: ["Code Checks"]
    types:
      - completed

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/download-artifact@v3
        with:
          name: osumffmpeg-source

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"

      - name: Linux build
        run: flutter build linux

      - name: Compress build
        run: tar -C build/linux/x64/release/bundle -cvf osumffmpeg-linux-x64-noffmpeg.tar.gz .

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: osumffmpeg-linux-x64-noffmpeg
          path: osumffmpeg-linux-x64-noffmpeg.tar.gz
