name: Linux Build

on:
  workflow_run:
    workflows: ["Code Checks"]
    types:
      - completed

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: checks.yml
          workflow_conclusion: success
          name: osumffmpeg-source

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
      
      # source: https://github.com/flutter/flutter/issues/59750
      - name: Patch for linux build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Linux build
        run: flutter build linux

      - name: Compress build
        run: tar -C build/linux/x64/release/bundle -cvf osumffmpeg-linux-x64-noffmpeg.tar.gz .

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: osumffmpeg-linux-x64-noffmpeg
          path: osumffmpeg-linux-x64-noffmpeg.tar.gz
