name: Windows Build

on:
  workflow_run:
    workflows: ["Code Checks"]
    types:
      - completed

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Get source
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: checks.yml
          workflow_conclusion: success
          name: osumffmpeg-source

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"

      - name: Windows build
        run: flutter build windows
      
      - name: Get upx
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install upx -y
      
      - name: Compress dlls
        run: upx build/windows/runner/Release/*.dll

      - name: Pack build
        run: tar -C build/windows/runner/Release -cvf osumffmpeg-windows-x64-noffmpeg.tar.gz .

      - name: Pack source
        run: tar -C . -cvf osumffmpeg-windows-x64-noffmpeg-source.tar.gz .

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: osumffmpeg-windows-x64-noffmpeg
          path: osumffmpeg-windows-x64-noffmpeg.tar.gz
      
      - name: Pack source
        uses: actions/upload-artifact@v2
        with:
          name: osumffmpeg-windows-x64-noffmpeg-source
          path: osumffmpeg-windows-x64-noffmpeg-source.tar.gz
